databases:
  - name: track-classifier-db
    plan: free
    databaseName: track_classifier
    user: track_classifier

services:
  - type: web
    name: wildlife-track-classifier
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: track-classifier-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        sync: false
